### ISSUE TITLE
Can't get libaudiodecoder to work with MS Visual Studio Community 2015

### ISSUE THREAD

**Issue by ghost** [asantoni/libaudiodecoder#2]
I'm wanting to use libaudiodecoder in my own project, but trying to build it gives errors. Trying to build the "playsong" example also gives me the same errors. I used Visual Studio 2015 to build the PortAudio libraries and dll's, and I used Scons to build the libaudiodecoder libraries and dll's. I also set the project to correctly link against those libraries and put the dll's in my project's directory. However, when I try to build the "playsong" project it outputs this:

1>------ Build started: Project: playsong, Configuration: Release Win32 ------
1>  playsong.cpp
1>c:\users\billm\documents\my_files\code\frameworks\libaudiodecoder\include\audiodecoderbase.h(106): warning C4251: 'AudioDecoderBase::m_filename': class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' needs to have dll-interface to be used by clients of class 'AudioDecoderBase'
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstring(2628): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
1>C:\Users\BillM\Documents\My_Files\Code\Frameworks\libaudiodecoder\include\audiodecoder.h(52): error C2512: 'AudioDecoderMediaFoundation': no appropriate default constructor available
1>  c:\users\billm\documents\my_files\code\frameworks\libaudiodecoder\include\audiodecodermediafoundation.h(27): note: see declaration of 'AudioDecoderMediaFoundation'
1>  C:\Users\BillM\Documents\My_Files\Code\Frameworks\libaudiodecoder\include\audiodecoder.h(52): note: This diagnostic occurred in the compiler generated function 'AudioDecoder::AudioDecoder(const AudioDecoder &)'
1>C:\Users\BillM\Documents\My_Files\Code\Frameworks\libaudiodecoder\include\audiodecoder.h(52): error C2437: 'AudioDecoderMediaFoundation': has already been initialized
1>  C:\Users\BillM\Documents\My_Files\Code\Frameworks\libaudiodecoder\include\audiodecoder.h(52): note: This diagnostic occurred in the compiler generated function 'AudioDecoder::AudioDecoder(const AudioDecoder &)'
1>C:\Users\BillM\Documents\My_Files\Code\Frameworks\libaudiodecoder\include\audiodecoder.h(52): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>  C:\Users\BillM\Documents\My_Files\Code\Frameworks\libaudiodecoder\include\audiodecoder.h(52): note: This diagnostic occurred in the compiler generated function 'AudioDecoder &AudioDecoder::operator =(const AudioDecoder &)'
1>C:\Users\BillM\Documents\My_Files\Code\Frameworks\libaudiodecoder\include\audiodecoder.h(52): error C2059: syntax error: 'AudioDecoderMediaFoundation'
1>  C:\Users\BillM\Documents\My_Files\Code\Frameworks\libaudiodecoder\include\audiodecoder.h(52): note: This diagnostic occurred in the compiler generated function 'AudioDecoder &AudioDecoder::operator =(const AudioDecoder &)'
1>C:\Users\BillM\Documents\My_Files\Code\Frameworks\libaudiodecoder\include\audiodecoder.h(52): error C2061: syntax error: identifier 'AudioDecoderMediaFoundation'
1>  C:\Users\BillM\Documents\My_Files\Code\Frameworks\libaudiodecoder\include\audiodecoder.h(52): note: This diagnostic occurred in the compiler generated function 'AudioDecoder &AudioDecoder::operator =(AudioDecoder &&)'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by ghost** [comment]
It seems like Visual Studio thinks there's something wrong with the constructor at line 51 of "audiodecoder.h". Nothing seems wrong with it though; it's like there's a bug in the actual compiler or something. Is there anything I can do?

**Comment by ghost** [comment]
Looking at the code closer, it may have something to do with line 19 in "audiodecodermediafoundation.h":

DllExport int AudioDecoderMediaFoundation = 1;

I think the compiler is confusing this integer with the AudioDecoderMediaFoundation class. What does this integer even do? It looks like it has something to do with dll exporting, but I don't understand what's happening in that line of code.

**Comment by asantoni** [comment]
Hi @ApothemBill, I think you've got the end of the string. I just cracked this open in MSVS 2012 and I think you might be right that the compiler-generated copy constructor and assignment operator code contain an error due to the use of that duplicate symbol. I don't know if that "DllExport int AudioDecoderMediaFoundation = 1;" hack is still necessary, but presumably it was at one point.

What you can try doing is preventing the compiler from generating a copy constructor and assignment operator, which generally a good practice in C++ anyways. 

In AudioDecoder.h, can you add this to the class declaration?

```
private:
    //Disable copy constructor and assignment operator
    AudioDecoder(const AudioDecoder& that);
    AudioDecoder& operator=(AudioDecoder const&);
```

**Comment by ghost** [comment]
Yes, adding those lines of code worked! Thank you!

Also, it works with line 19 of "audiodecodermediafoundation.h" left in:
`DllExport int AudioDecoderMediaFoundation = 1;`
and it works with it commented out:
`//DllExport int AudioDecoderMediaFoundation = 1;`

So should that hack be left in or taken out?
