### ISSUE TITLE
audiodecodermediafoundation.cpp identifies as GPL

### ISSUE THREAD

**Issue by Hendricks266** [asantoni/libaudiodecoder#4]
The README.md of the project states that libaudiodecoder is under the MIT license, but audiodecodermediafoundation.cpp contains a block comment stating it is under the GPL v2 or later. If the entire project is truly under the MIT license, then this comment should be removed (with no effect on any GPL projects using the library) and replaced with the MIT header from the other files. audiodecodermediafoundation.h could benefit from the same header.

**Comment by asantoni** [comment]
Hi Evan,

Those GPL headers are indeed a mistake. The code originated from a part of
Mixxx but the original authors of this code all agreed to relicense it
under the MIT license. Thanks for spotting that and I'd gladly accept a
pull request that removes or corrects those comments in the files.

Thanks!
Albert
