### ISSUE TITLE
x86_amd64 build fails

### ISSUE THREAD

**Issue by AJ92** [asantoni/libaudiodecoder#7]
if i specify x86 as target architecture i can build the lib
if i used x86_amd64 as target architecture scons can't find the windows media foundation libs...

no idea why... i have the win 7 sdk installed

os in use is win10

**Comment by asantoni** [comment]
Can you paste your config.log? It gets created after you run scons and
usually sheds light on what compiler flags are being used.

**Comment by AJ92** [comment]
didn't expected such a fast reply ... was under the shower :)

config.log:

file C:\Code\VS\engine-main\libaudiodecoder\src\SConscript,line 97:
	Configure(confdir = .sconf_temp)
scons: Configure: Checking for C library Mf... 
scons: Configure: ".sconf_temp\conftest_0.c" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp\conftest_0.c <-
  |  |
  |  |
  |  |
  |  |int
  |  |main() {
  |  |  
  |  |return 0;
  |  |}
  |  |
  |
cl /Fo.sconf_temp\conftest_0.obj /c .sconf_temp\conftest_0.c /nologo "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /Isrc /Iinclude
conftest_0.c
Using tempfile c:\users\aj\appdata\local\temp\tmppsrdnh.lnk for command line:
link /nologo /OUT:.sconf_temp\conftest_0.exe /LIBPATH:C:\Windows\Microsoft.NET\Framework\v4.0.30319 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\UnionMetadata" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.UniversalApiContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.FoundationContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\indows.Networking.Connectivity.WwanContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral" /LIBPATH:C:\Windows\Microsoft.NET\Framework\v4.0.30319 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\UnionMetadata" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.UniversalApiContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.FoundationContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\indows.Networking.Connectivity.WwanContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral" /LIBPATH:C:\Windows\Microsoft.NET\Framework\v4.0.30319 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\UnionMetadata" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.UniversalApiContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.FoundationContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\indows.Networking.Connectivity.WwanContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral" Mf.lib .sconf_temp\conftest_0.obj
link @c:\users\aj\appdata\local\temp\tmppsrdnh.lnk
LINK : error LNK2001: unresolved external symbol mainCRTStartup
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\LIBCMT.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
.sconf_temp\conftest_0.exe : fatal error LNK1120: 1 unresolved externals
scons: Configure: no

**Comment by asantoni** [comment]
Sorry, I'm on mobile at the moment, so I might have missed this. Are you
compiling with "scons target_arch=x64" ?

**Comment by AJ92** [comment]
here are the msvc compiler options:

    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\vc\vcvarsall.bat" [option]
  or
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\vc\vcvarsall.bat" [option] store
where [option] is: x86 | amd64 | arm | x86_amd64 | x86_arm | amd64_x86 | amd64_arm

The store parameter sets environment variables to support
  store (rather than desktop) development.

For example:
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\vc\vcvarsall.bat" x86_amd64
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\vc\vcvarsall.bat" x86_arm store



i used target_arch=x86_amd64

looks like x86_64 produces the same output

amd64_x86 doesn't work with scons

**Comment by asantoni** [comment]
Another thing is if you want to try troubleshooting this further before I
can get to it, look at the src/SConscript file in the repository and see if
you can figure out if there's an /X86 flag or something hard coded where it
shouldn't be. The SConscript file is written in Python and it's fairly
readable, hopefully.

**Comment by asantoni** [comment]
amd64 should be the one you use then, I think. Can you try that and paste
your config.log again after that?

**Comment by AJ92** [comment]
give me a second

direct console output:
scons: Reading SConscript files ...

scons: warning: The build_dir keyword has been deprecated; use the variant_dir keyword instead.
File "C:\Code\VS\engine-main\libaudiodecoder\SConstruct", line 1, in <module>
Checking for C library Mf... no
Did not find Windows Media Foundation .lib files. Do you have the Windows 7 Platform SDK installed?


config.log:
file C:\Code\VS\engine-main\libaudiodecoder\src\SConscript,line 97:
	Configure(confdir = .sconf_temp)
scons: Configure: Checking for C library Mf... 
scons: Configure: ".sconf_temp\conftest_0.c" is up to date.
scons: Configure: The original builder output was:
  |.sconf_temp\conftest_0.c <-
  |  |
  |  |
  |  |
  |  |int
  |  |main() {
  |  |  
  |  |return 0;
  |  |}
  |  |
  |
cl /Fo.sconf_temp\conftest_0.obj /c .sconf_temp\conftest_0.c /nologo "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /Isrc /Iinclude
conftest_0.c
Using tempfile c:\users\aj\appdata\local\temp\tmpfgecxc.lnk for command line:
link /nologo /OUT:.sconf_temp\conftest_0.exe /LIBPATH:C:\Windows\Microsoft.NET\Framework\v4.0.30319 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\UnionMetadata" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.UniversalApiContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.FoundationContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\indows.Networking.Connectivity.WwanContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral" /LIBPATH:C:\Windows\Microsoft.NET\Framework\v4.0.30319 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\UnionMetadata" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.UniversalApiContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.FoundationContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\indows.Networking.Connectivity.WwanContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral" /LIBPATH:C:\Windows\Microsoft.NET\Framework\v4.0.30319 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\UnionMetadata" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.UniversalApiContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.FoundationContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\References\indows.Networking.Connectivity.WwanContract\1.0.0.0" "/LIBPATH:C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral" Mf.lib .sconf_temp\conftest_0.obj
link @c:\users\aj\appdata\local\temp\tmpfgecxc.lnk
LINK : error LNK2001: unresolved external symbol mainCRTStartup
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\LIBCMT.lib : warning LNK4272: library machine type 'X86' conflicts with target machine type 'x64'
.sconf_temp\conftest_0.exe : fatal error LNK1120: 1 unresolved externals
scons: Configure: no



looks like LIBCMT is 32bit and conflicts with the project?

**Comment by AJ92** [comment]
i could solve the problem...
the issue is hidden in the vcvarsall.bat which sets up some env vars for the terminal...
apparently it sets 32 bit vars by default...

so insetad of pointing to the vcvarsall.bat i pointed to the 64bit bat directly (vcvars64.bat) in a different directory...

so the final build command looks like this:

`"C:\Program Files (x86)\Microsoft Visual Studio 14.0\vc\bin\amd64\vcvars64.bat"
scons debug=1 msvc_version=14.0 target_arch=x86_64`
